### ISSUE TITLE
New coefficients table issue

### ISSUE THREAD

**Issue by northernbio** [LandSciTech/caribouMetrics#107]
When I try using a new coefficients table for the caribouHabitat model, I get the same predicted RSF values as when using the coefficients provided in the original table (coefTableHR).  I loaded the original and revised grds into QGIS to explore, and the same predicted values occurred.  Code is revised from 2_CaribouHabitatMississa.R.  I added anthroDist = file.path(dat_pth, "mines_ras.tif")

#globally change some coefficient values to - 5 for testing.
coefTabRevised2 <- coefTableHR %>%
  mutate(Coefficient = ifelse(Variable %in% c("ST", "CON"), -5, Coefficient))

remove(carHab_Mis)

# Missisa
carHab_Mis <- caribouHabitat(
  landCover = file.path(dat_pth, "plc250.tif"),
  esker = file.path(dat_pth, "esker.shp"),
  natDist = file.path(dat_pth, "fireAFFES2010_250.tif"),
  anthroDist = file.path(dat_pth, "mines_ras.tif"),
  linFeat = list(roads = file.path(dat_pth, "road_ORNMNRFMiss2010.shp"),
                 rail = file.path(dat_pth, "rail.shp"),
                 utilities = file.path(dat_pth, "util2010.shp")),
  projectPoly = missisa,
  caribouRange = "Missisa",
  coefTable = coefTabRevised2,
  #coefTable = coefTableHR,
  #padFocal = TRUE, # assume data outside area is 0 for all variables
  padProjPoly=TRUE,
  saveOutput = "outputs/missisa_2010_HabUseRevised2.grd"
  #saveOutput = "outputs/missisa_2010_HabUseOriginal.grd"
)

**Comment by see24** [comment]
Thanks for reporting this Rob! There was a spot where the table was accidentally not passed on to the next function so the default coefTableHR was being use. Please re-install from GitHub and let me know if your example works now.
